services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=userservice,postservice
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    networks:
      - app-network

  clickhouse:
    image: clickhouse/clickhouse-server:22.8
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "22181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - app-network

  user-service:
    build: ./user_service
    depends_on:
      - postgres
      - kafka
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/userservice
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - JWT_SECRET=thenromanov-secret-key
      - GRPC_PORT=50051
    networks:
      - app-network

  post-service:
    build: ./post_service
    depends_on:
      - postgres
      - kafka
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postservice
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - JWT_SECRET=thenromanov-secret-key
      - GRPC_PORT=50052
    networks:
      - app-network

  stats-service:
    build: ./stats_service
    depends_on:
      - clickhouse
      - kafka
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DB=default
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_GROUP_ID=stats-service
      - GRPC_PORT=50053
    networks:
      - app-network

  api-gateway:
    build: ./api_gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - post-service
      - stats-service
    environment:
      - USER_SERVICE_ADDRESS=user-service:50051
      - POST_SERVICE_ADDRESS=post-service:50052
      - STATS_SERVICE_ADDRESS=stats-service:50053
      - JWT_SECRET=thenromanov-secret-key
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  clickhouse-data:
