services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=userservice
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d userservice" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  user-service:
    build: ./user_service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/userservice
      - JWT_SECRET=your_secure_jwt_secret
    networks:
      - app-network

  api-gateway:
    build: ./api_gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
    environment:
      - USER_SERVICE_ADDRESS=user-service:50051
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
