# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stats.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstats.proto\x12\x05stats\"#\n\x10PostStatsRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\"C\n\x11PostStatsResponse\x12\r\n\x05views\x18\x01 \x01(\x03\x12\r\n\x05likes\x18\x02 \x01(\x03\x12\x10\n\x08\x63omments\x18\x03 \x01(\x03\"L\n\x13PostTimelineRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\",\n\rTimelineEntry\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"=\n\x14PostTimelineResponse\x12%\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x14.stats.TimelineEntry\"\x80\x01\n\nTopRequest\x12\x31\n\x0bmetric_type\x18\x01 \x01(\x0e\x32\x1c.stats.TopRequest.MetricType\x12\r\n\x05limit\x18\x02 \x01(\x05\"0\n\nMetricType\x12\t\n\x05VIEWS\x10\x00\x12\t\n\x05LIKES\x10\x01\x12\x0c\n\x08\x43OMMENTS\x10\x02\"=\n\x0cTopPostEntry\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x03\"@\n\x0cTopUserEntry\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x03\"6\n\x10TopPostsResponse\x12\"\n\x05posts\x18\x01 \x03(\x0b\x32\x13.stats.TopPostEntry\"6\n\x10TopUsersResponse\x12\"\n\x05users\x18\x01 \x03(\x0b\x32\x13.stats.TopUserEntry2\xbd\x03\n\x0cStatsService\x12\x41\n\x0cGetPostStats\x12\x17.stats.PostStatsRequest\x1a\x18.stats.PostStatsResponse\x12O\n\x14GetPostViewsTimeline\x12\x1a.stats.PostTimelineRequest\x1a\x1b.stats.PostTimelineResponse\x12O\n\x14GetPostLikesTimeline\x12\x1a.stats.PostTimelineRequest\x1a\x1b.stats.PostTimelineResponse\x12R\n\x17GetPostCommentsTimeline\x12\x1a.stats.PostTimelineRequest\x1a\x1b.stats.PostTimelineResponse\x12\x39\n\x0bGetTopPosts\x12\x11.stats.TopRequest\x1a\x17.stats.TopPostsResponse\x12\x39\n\x0bGetTopUsers\x12\x11.stats.TopRequest\x1a\x17.stats.TopUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTSTATSREQUEST']._serialized_start=22
  _globals['_POSTSTATSREQUEST']._serialized_end=57
  _globals['_POSTSTATSRESPONSE']._serialized_start=59
  _globals['_POSTSTATSRESPONSE']._serialized_end=126
  _globals['_POSTTIMELINEREQUEST']._serialized_start=128
  _globals['_POSTTIMELINEREQUEST']._serialized_end=204
  _globals['_TIMELINEENTRY']._serialized_start=206
  _globals['_TIMELINEENTRY']._serialized_end=250
  _globals['_POSTTIMELINERESPONSE']._serialized_start=252
  _globals['_POSTTIMELINERESPONSE']._serialized_end=313
  _globals['_TOPREQUEST']._serialized_start=316
  _globals['_TOPREQUEST']._serialized_end=444
  _globals['_TOPREQUEST_METRICTYPE']._serialized_start=396
  _globals['_TOPREQUEST_METRICTYPE']._serialized_end=444
  _globals['_TOPPOSTENTRY']._serialized_start=446
  _globals['_TOPPOSTENTRY']._serialized_end=507
  _globals['_TOPUSERENTRY']._serialized_start=509
  _globals['_TOPUSERENTRY']._serialized_end=573
  _globals['_TOPPOSTSRESPONSE']._serialized_start=575
  _globals['_TOPPOSTSRESPONSE']._serialized_end=629
  _globals['_TOPUSERSRESPONSE']._serialized_start=631
  _globals['_TOPUSERSRESPONSE']._serialized_end=685
  _globals['_STATSSERVICE']._serialized_start=688
  _globals['_STATSSERVICE']._serialized_end=1133
# @@protoc_insertion_point(module_scope)
